version: "3.8"
name: "tymsa-test"

services:
  db:
    image: postgres:15-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_NAME
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 2s
      timeout: 1s
      retries: 3

  api:
    image: ${REGISTRY_HOST_USERNAME}/tymsa-api:test
    command: gunicorn tymsa.wsgi:application --bind 0.0.0.0:8001
    restart: unless-stopped
    ports:
      - "18001:8001"
    environment:
      - DJANGO_DEBUG
      - DJANGO_SECRET_KEY
      - DJANGO_ALLOWED_HOSTS
      - POSTGRES_DB
      - POSTGRES_NAME
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST
      - POSTGRES_PORT
    depends_on:
      db:
        condition: service_healthy

  client:
    image: ${REGISTRY_HOST_USERNAME}/tymsa:test
    command: node ./dist/server/entry.mjs
    restart: unless-stopped
    ports:
      - "14321:4321"
    environment:
      - BASE_PATH
    depends_on:
      - api

volumes:
  db-data:
