name: Deploy on release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  deploy:
    runs_on: ubuntu-latest
    container:
      image: catthehacker/ubuntu:act-latest
    steps:
      - name: Get docker-compose content
        id: compose
        uses: jaywcjlove/github-action-read-file@main
        with:
          path: docker-compose.yml

      - name: Tag and deploy to Docker via SSH
        uses: appleboy/ssh-action@v1.0.0
        env:
          ENV_FILE: ${{ secrets.ENV_FILE }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          envs: ENV_FILE
          script: |
            mkdir -p ./tymsa
            cd ./tymsa

            echo '${{ secrets.ENV_FILE }}' > .env
            echo '${{ steps.compose.outputs.content }}' > docker-compose.yml

            docker login ${{ secrets.REGISTRY_HOST }} --username=${{ secrets.REGISTRY_USERNAME }} --password=${{ secrets.REGISTRY_PASSWORD }}

            docker compose down

            docker pull ${{ secrets.REGISTRY_HOST_USERNAME }}/tymsa:candidate
            docker pull ${{ secrets.REGISTRY_HOST_USERNAME }}/tymsa-api:candidate

            docker tag ${{ secrets.REGISTRY_HOST_USERNAME }}/tymsa:candidate ${{ secrets.REGISTRY_HOST_USERNAME }}/tymsa:${{ gitea.ref_name }}
            docker tag ${{ secrets.REGISTRY_HOST_USERNAME }}/tymsa-api:candidate ${{ secrets.REGISTRY_HOST_USERNAME }}/tymsa-api:${{ gitea.ref_name }}

            docker tag ${{ secrets.REGISTRY_HOST_USERNAME }}/tymsa:candidate ${{ secrets.REGISTRY_HOST_USERNAME }}/tymsa:latest
            docker tag ${{ secrets.REGISTRY_HOST_USERNAME }}/tymsa-api:candidate ${{ secrets.REGISTRY_HOST_USERNAME }}/tymsa-api:latest

            docker push ${{ secrets.REGISTRY_HOST_USERNAME }}/tymsa:${{ gitea.ref_name }}
            docker push ${{ secrets.REGISTRY_HOST_USERNAME }}/tymsa-api:${{ gitea.ref_name }}

            docker push ${{ secrets.REGISTRY_HOST_USERNAME }}/tymsa:latest
            docker push ${{ secrets.REGISTRY_HOST_USERNAME }}/tymsa-api:latest

            docker compose up -d

            docker system prune -f