# Generated by Django 5.0 on 2023-12-10 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='start_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
