# Generated by Django 5.0 on 2023-12-10 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0002_alter_timer_start_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='end_datetime',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
