# Generated by Django 5.0 on 2023-12-10 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0003_alter_timer_end_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='timer',
            name='duration',
            field=models.DurationField(blank=True, editable=False, null=True),
        ),
    ]
