# Generated by Django 5.0 on 2023-12-17 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('timer', '0004_timer_duration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timer',
            options={'get_latest_by': 'start_datetime'},
        ),
        migrations.AlterField(
            model_name='timer',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
    ]
