# Generated by Django 5.0 on 2023-12-30 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0005_alter_timer_options_alter_timer_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='note',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
