# Generated by Django 5.0 on 2024-01-06 14:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0006_alter_timer_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timer',
            name='start_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
