# Generated by Django 5.0 on 2024-01-11 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0007_alter_timer_end_datetime_alter_timer_start_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='timer',
            name='previous',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='timer.timer'),
        ),
    ]
