/* tslint:disable */
/* eslint-disable */
/**
 * Tymr API
 * API for Tymr time-tracking
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedTimer
 */
export interface PatchedTimer {
    /**
     * 
     * @type {string}
     * @memberof PatchedTimer
     */
    readonly url?: string;
    /**
     * 
     * @type {number}
     * @memberof PatchedTimer
     */
    readonly timesince?: number;
    /**
     * 
     * @type {Date}
     * @memberof PatchedTimer
     */
    readonly startDatetime?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PatchedTimer
     */
    endDatetime?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedTimer
     */
    note?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedTimer
     */
    project?: string;
}

/**
 * Check if a given object implements the PatchedTimer interface.
 */
export function instanceOfPatchedTimer(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PatchedTimerFromJSON(json: any): PatchedTimer {
    return PatchedTimerFromJSONTyped(json, false);
}

export function PatchedTimerFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedTimer {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'url': !exists(json, 'url') ? undefined : json['url'],
        'timesince': !exists(json, 'timesince') ? undefined : json['timesince'],
        'startDatetime': !exists(json, 'start_datetime') ? undefined : (new Date(json['start_datetime'])),
        'endDatetime': !exists(json, 'end_datetime') ? undefined : (json['end_datetime'] === null ? null : new Date(json['end_datetime'])),
        'note': !exists(json, 'note') ? undefined : json['note'],
        'project': !exists(json, 'project') ? undefined : json['project'],
    };
}

export function PatchedTimerToJSON(value?: PatchedTimer | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'end_datetime': value.endDatetime === undefined ? undefined : (value.endDatetime === null ? null : value.endDatetime.toISOString()),
        'note': value.note,
        'project': value.project,
    };
}

