/* tslint:disable */
/* eslint-disable */
/**
 * Tymr API
 * API for Tymr time-tracking
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Timer
 */
export interface Timer {
    /**
     * 
     * @type {string}
     * @memberof Timer
     */
    readonly url: string;
    /**
     * 
     * @type {number}
     * @memberof Timer
     */
    readonly timesince: number;
    /**
     * 
     * @type {Date}
     * @memberof Timer
     */
    readonly startDatetime: Date;
    /**
     * 
     * @type {Date}
     * @memberof Timer
     */
    endDatetime?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof Timer
     */
    note?: string;
    /**
     * 
     * @type {string}
     * @memberof Timer
     */
    project: string;
}

/**
 * Check if a given object implements the Timer interface.
 */
export function instanceOfTimer(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "url" in value;
    isInstance = isInstance && "timesince" in value;
    isInstance = isInstance && "startDatetime" in value;
    isInstance = isInstance && "project" in value;

    return isInstance;
}

export function TimerFromJSON(json: any): Timer {
    return TimerFromJSONTyped(json, false);
}

export function TimerFromJSONTyped(json: any, ignoreDiscriminator: boolean): Timer {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'url': json['url'],
        'timesince': json['timesince'],
        'startDatetime': (new Date(json['start_datetime'])),
        'endDatetime': !exists(json, 'end_datetime') ? undefined : (json['end_datetime'] === null ? null : new Date(json['end_datetime'])),
        'note': !exists(json, 'note') ? undefined : json['note'],
        'project': json['project'],
    };
}

export function TimerToJSON(value?: Timer | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'end_datetime': value.endDatetime === undefined ? undefined : (value.endDatetime === null ? null : value.endDatetime.toISOString()),
        'note': value.note,
        'project': value.project,
    };
}

