/* tslint:disable */
/* eslint-disable */
/**
 * Tymsa API
 * API for Tymsa time-tracking
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedTimerUpdateTimes
 */
export interface PatchedTimerUpdateTimes {
    /**
     * 
     * @type {Date}
     * @memberof PatchedTimerUpdateTimes
     */
    readonly startDatetime?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PatchedTimerUpdateTimes
     */
    endDatetime?: Date | null;
}

/**
 * Check if a given object implements the PatchedTimerUpdateTimes interface.
 */
export function instanceOfPatchedTimerUpdateTimes(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PatchedTimerUpdateTimesFromJSON(json: any): PatchedTimerUpdateTimes {
    return PatchedTimerUpdateTimesFromJSONTyped(json, false);
}

export function PatchedTimerUpdateTimesFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedTimerUpdateTimes {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'startDatetime': !exists(json, 'start_datetime') ? undefined : (new Date(json['start_datetime'])),
        'endDatetime': !exists(json, 'end_datetime') ? undefined : (json['end_datetime'] === null ? null : new Date(json['end_datetime'])),
    };
}

export function PatchedTimerUpdateTimesToJSON(value?: PatchedTimerUpdateTimes | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'end_datetime': value.endDatetime === undefined ? undefined : (value.endDatetime === null ? null : value.endDatetime.toISOString()),
    };
}

