/* tslint:disable */
/* eslint-disable */
/**
 * Tymr API
 * API for Tymr time-tracking
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedProject
 */
export interface PatchedProject {
    /**
     * 
     * @type {number}
     * @memberof PatchedProject
     */
    readonly id?: number;
    /**
     * 
     * @type {string}
     * @memberof PatchedProject
     */
    readonly url?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedProject
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedProject
     */
    color?: string;
}

/**
 * Check if a given object implements the PatchedProject interface.
 */
export function instanceOfPatchedProject(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PatchedProjectFromJSON(json: any): PatchedProject {
    return PatchedProjectFromJSONTyped(json, false);
}

export function PatchedProjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedProject {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'url': !exists(json, 'url') ? undefined : json['url'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'color': !exists(json, 'color') ? undefined : json['color'],
    };
}

export function PatchedProjectToJSON(value?: PatchedProject | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'color': value.color,
    };
}

