/* tslint:disable */
/* eslint-disable */
/**
 * Tymsa API
 * API for Tymsa time-tracking
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProjectRead
 */
export interface ProjectRead {
    /**
     * 
     * @type {number}
     * @memberof ProjectRead
     */
    readonly id: number;
    /**
     * 
     * @type {string}
     * @memberof ProjectRead
     */
    readonly name: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectRead
     */
    readonly color: string;
}

/**
 * Check if a given object implements the ProjectRead interface.
 */
export function instanceOfProjectRead(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "color" in value;

    return isInstance;
}

export function ProjectReadFromJSON(json: any): ProjectRead {
    return ProjectReadFromJSONTyped(json, false);
}

export function ProjectReadFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectRead {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'color': json['color'],
    };
}

export function ProjectReadToJSON(value?: ProjectRead | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
    };
}

