/* tslint:disable */
/* eslint-disable */
/**
 * Tymr API
 * API for Tymr time-tracking
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TimerUpdate
 */
export interface TimerUpdate {
    /**
     * 
     * @type {number}
     * @memberof TimerUpdate
     */
    readonly id: number;
    /**
     * 
     * @type {Date}
     * @memberof TimerUpdate
     */
    readonly startDatetime: Date;
    /**
     * 
     * @type {Date}
     * @memberof TimerUpdate
     */
    readonly endDatetime: Date | null;
    /**
     * 
     * @type {string}
     * @memberof TimerUpdate
     */
    note?: string;
    /**
     * 
     * @type {string}
     * @memberof TimerUpdate
     */
    readonly duration: string | null;
    /**
     * 
     * @type {number}
     * @memberof TimerUpdate
     */
    project?: number | null;
}

/**
 * Check if a given object implements the TimerUpdate interface.
 */
export function instanceOfTimerUpdate(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "startDatetime" in value;
    isInstance = isInstance && "endDatetime" in value;
    isInstance = isInstance && "duration" in value;

    return isInstance;
}

export function TimerUpdateFromJSON(json: any): TimerUpdate {
    return TimerUpdateFromJSONTyped(json, false);
}

export function TimerUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimerUpdate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'startDatetime': (new Date(json['start_datetime'])),
        'endDatetime': (json['end_datetime'] === null ? null : new Date(json['end_datetime'])),
        'note': !exists(json, 'note') ? undefined : json['note'],
        'duration': json['duration'],
        'project': !exists(json, 'project') ? undefined : json['project'],
    };
}

export function TimerUpdateToJSON(value?: TimerUpdate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'note': value.note,
        'project': value.project,
    };
}

